### ISSUE TITLE
MP3s saving as WebMs

### ISSUE THREAD

**Issue by Mennaruuk** [devnazir/yt-downloader#1]
Whenever I download the video as MP3, it's instead saved as WebM. Is there a way to force change the file extension to MP3 server side, or just rename the option MP3 to WEBM?

Another thing I noticed is when I search for videos on yt-downloader, the Download button only downloads video. I think it'd be awesome to also include an option to download the audio stream. Maybe it can be a dropdown menu!

Thanks a lot :)

**Comment by devnazir** [comment]
thank you for your advice and create new issues first time, this website still many issues. Maybe I will update this repo again

**Comment by Mennaruuk** [comment]
No problem! Love using your tool, pretty easy. Not a big issue, I like webm anyway.
